### ISSUE TITLE
Cannot import library

### ISSUE THREAD

**Issue by pmdbt** [vmanikes/Lyft-Python-SDK#6]
Hi, I've run into a pretty weird issue here. I downloaded the module via pip just like in the example you guys provided. Here is the result from my terminal. 

`Jerrys-MacBook-Pro:foresight jerrychu$ pip3 install lyft-python
Collecting lyft-python
  Downloading https://files.pythonhosted.org/packages/91/5b/5355e2d48b0593277d01ef0ccfba68488fd5111e3a25dba4213caa6d89e1/lyft-python-0.1.1.tar.gz
Building wheels for collected packages: lyft-python
Running setup.py bdist_wheel for lyft-python ... done   
Stored in directory: /Users/jerrychu/Library/Caches/pip/wheels/c1/e2/41/22c4828645feab2caa5356df84d102e41fd6cc97241bf258c2
Successfully built lyft-python
Installing collected packages: lyft-python
Successfully installed lyft-python-0.1.1
`

I then wrote the following code based off of one of your examples:

```python
from lyft.authentication import LyftPublicAuth

#constants for API authentication
CLIENT_ID = '***'
CLIENT_SECRET = '***'
CLIENT_TOKEN = '***'

def test_fetcher(id, secret):
    auth = LyftPublicAuth(
                            {
                                "client_id": id,
                                "client_secret": secret
                            },
                            sandbox_mode=True
                        )
    token_rate_limits = auth.access_token()
    return token_rate_limits

print(test_fetcher(CLIENT_ID, CLIENT_SECRET))
```

But oddly when I tried to run this code, I received the following error:

```
Jerrys-MacBook-Pro:foresight jerrychu$ python3 test_lyft_fetcher.py
Traceback (most recent call last):
  File "test_lyft_fetcher.py", line 1, in <module>
    from lyft.authentication import LyftPublicAuth
ImportError: cannot import name 'LyftPublicAuth'
```

Any ideas on what's causing this and how to fix it?

**Comment by vmanikes** [comment]
That's a strange error. Let me check that

**Comment by vmanikes** [comment]
I fixed the readme, so you can import like this and its not `access_token()` its `get_access_token()`
```
from lyft.authentication.auth import LyftPublicAuth

#constants for API authentication
CLIENT_ID = ''
CLIENT_SECRET = ''
CLIENT_TOKEN = ''

auth = LyftPublicAuth({"client_id": CLIENT_ID, "client_secret": CLIENT_SECRET}, sandbox_mode=True)
print(auth.get_access_token())

```

**Comment by pmdbt** [comment]
Hi vmanikes, thanks for getting back to me on this issue! I copied and pasted your fix, and filled in the credentials with my own credentials. While the original issue has been resolved, I'm getting a different error now. Here is the code and resulting ouptut:

```python
from lyft.authentication.auth import LyftPublicAuth

#constants for API authentication
CLIENT_ID = '***'
CLIENT_SECRET = '***'
CLIENT_TOKEN = '***'

auth = LyftPublicAuth({"client_id": CLIENT_ID, "client_secret": CLIENT_SECRET}, sandbox_mode = True)
print(auth.access_token())
```
`
Jerrys-MacBook-Pro:foresight jerrychu$ python3 test_lyft_fetcher.py
Traceback (most recent call last):
  File "test_lyft_fetcher.py", line 9, in <module>
    print(auth.access_token())
AttributeError: 'LyftPublicAuth' object has no attribute 'access_token'
`

**Comment by vmanikes** [comment]
Quick question are you using 2 legged or 3 legged auth, if 3 legged auth use get_access_token()

**Comment by pmdbt** [comment]
I'm trying to use 2 legged authentication. I just want to be able to get the number of nearby drivers when inputing a gps coordinate, as well as ETA for a driver to reach that pickup location.

**Comment by vmanikes** [comment]
https://github.com/vmanikes/Lyft-Python-SDK/blob/master/lyft/authentication/auth.py#L22 
Its `get_access_token()`. Sorry about that I have updated the Readme

**Comment by pmdbt** [comment]
Ok, it works now! Thank you so much for your fast response, and I hope you guys maintain this library in the future. From the documentation alone, it sounds super useful!

**Comment by vmanikes** [comment]
Thanks for the compliment, Do you mind if I close this issue if it solved your problem?

**Comment by pmdbt** [comment]
Feel free to close this! The problem has been resolved.
